spring.application.name=RevatureWorkForceP2

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080
# ===============================
# ORACLE DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=revworkforcesecondproject
spring.datasource.password=revworkforcesecondproject123

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
=======
spring.jpa.hibernate.ddl-auto=create
>>>>>>> b09ad693854b4496e321429ab9250ea0c6c408cf
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# THYMELEAF CONFIG
# ===============================
spring.thymeleaf.cache=false


# LOGGING
<<<<<<< HEAD
logging.file.name=logs/revworkforce.log
logging.level.com.rev.app=INFO
logging.level.com.rev.app.config.ApplicationLoggingAspect=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=INFO
=======
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
>>>>>>> b09ad693854b4496e321429ab9250ea0c6c408cf
